# Generated by Django 5.1.6 on 2025-03-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='CourseTitle',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='Department',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Instructor',
            field=models.TextField(blank=True),
        ),
    ]
