# Generated by Django 5.1.6 on 2025-03-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0002_rename_content_post_coursetitle_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Course',
        ),
    ]
